name: C/C++ CI

on:
  push:
    branches: [ "main" , "dev" ]
  pull_request:
    branches: [ "main" , "dev"]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Install analysis tools
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg lsb-release
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 12
        sudo apt-get install -y clang-tidy-12
        clang-tidy-12 --version
        pip install scan-build
        which scan-build
    - name: static checks
      run: make tidy
    - name: format
      run: make formator
    - name: tidy
      run: make tidy
