name: C/C++ CI

on:
  push:
    branches: [ "main" , "dev" ]
  pull_request:
    branches: [ "main" , "dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install clang-tools
      run: |
        sudo apt-get update
        sudo apt-get install -y clang
        pip install scan-build
        which scan-build
    
    - name: make
      run: make
    - name: format
      run: make formator
    - name: tidy
      run: make tidy
